import { useState } from 'react';
import { useNavigate,useParams } from 'react-router-dom';
import styled from 'styled-components';
import Toast from '../components/Toast';
import { usePlivyStore } from '../store/PlivyStore';

const Page=styled.main`
 min-height:100vh;background:#f5f2ea;padding-bottom:95px;color:inherit;header{height:50px;display:grid;grid-template-columns:50px 1fr 50px;align-items:center;background:#c4d9a7;border-bottom:1px solid #92a77d}header h1{text-align:center;font:700 15px/1 var(--font-mono);letter-spacing:.15em}header button{height:50px;font-size:24px}.top-share{justify-self:center;width:34px!important;height:34px!important;border:1px solid #8fa178!important;border-radius:50%;font-size:17px!important}.body{padding:20px}
 .photo{width:100%;aspect-ratio:4/3;border-radius:10px;overflow:hidden;background:#d8d3df;display:grid;place-items:center}.photo img{width:100%;height:100%;object-fit:cover}.track{margin-top:16px;padding:14px;border:1px solid #ddd9df;border-radius:10px;background:#fff}.track strong{display:block}.track small{display:block;margin-top:5px;color:#888}.tags{display:flex;flex-wrap:wrap;gap:7px;margin:14px 0}.tags button{padding:7px 10px;border:1px solid #ded5e7;border-radius:16px;background:#f3eef5;color:#5d00ef;font-size:10px}.meta,.memo{padding:14px;border:1px solid #ddd9df;border-radius:10px;background:#fff}.meta{display:grid;grid-template-columns:1fr 1fr;gap:12px}.meta small{display:block;color:#999;font:8px var(--font-mono)}.meta b{display:block;margin-top:4px;font-size:11px}.memo{margin-top:12px;font-size:13px;line-height:1.7}.actions{display:grid;grid-template-columns:58px 62px minmax(0,1fr) 58px;gap:7px;margin-top:16px}.actions button{min-width:0;height:46px;padding:0 5px;white-space:nowrap;border:1px solid #ddd7e2;border-radius:12px;background:#fff;font-size:9px}.actions .active{color:#c72f63;border-color:#c72f63;background:#fff4f7}.actions .primary{background:#5d00ef;color:#fff;border-color:#5d00ef;font-size:9px;box-shadow:0 7px 15px rgba(93,0,239,.18)}.actions .danger{color:#9e294f;border-color:#e6bfd0;background:#fff7fa}.picker{margin-top:9px;padding:10px;border:1px solid #ddd7e2;border-radius:10px;background:#fff}.picker p{font-size:11px}.picker button{display:block;width:100%;padding:10px;text-align:left;border-top:1px solid #eee}.empty{padding:70px 20px;text-align:center}.empty button{margin-top:18px;padding:12px 18px;border-radius:10px;background:#5d00ef;color:white}
 html[data-theme='dark'] &{background:#181a20;color:#f2f2f5}html[data-theme='dark'] & header{background:#2e3a2e}html[data-theme='dark'] & .track,html[data-theme='dark'] & .meta,html[data-theme='dark'] & .memo,html[data-theme='dark'] & .actions button,html[data-theme='dark'] & .picker{background:#24262d;border-color:#41444d;color:#f2f2f5}
`;
export default function FeatureDetail(){
 const navigate=useNavigate();const {id=''}=useParams();const {records,playlists,likedRecordIds,toggleRecordLike,addToPlaylist,deleteRecord}=usePlivyStore();const record=records.find(r=>r.id===id);const [picker,setPicker]=useState(false);const [toast,setToast]=useState('');
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),1600)};
 if(!record)return <Page><header><button onClick={()=>navigate(-1)}>‹</button><h1>MEMORY DETAIL</h1><span/></header><div className="empty"><p>이 기록을 찾을 수 없어요.</p><button onClick={()=>navigate('/records',{replace:true})}>기록 목록으로</button></div></Page>;
 const liked=likedRecordIds.includes(record.id);
 const share=async()=>{const url=location.href;try{if(navigator.share){await navigator.share({title:record.title,text:record.memo,url});notify('공유 메뉴를 열었어요.')}else{await navigator.clipboard.writeText(url);notify('링크가 복사되었어요.')}}catch{notify('공유를 취소했어요.')}};
 const remove=()=>{if(!window.confirm('이 기록을 삭제할까요? 삭제한 기록은 되돌릴 수 없어요.'))return;deleteRecord(record.id);navigate('/records',{replace:true});};
 return <Page className="detail-page"><header><button onClick={()=>navigate(-1)}>‹</button><h1>MEMORY DETAIL</h1><button className="top-share" onClick={share} aria-label="기록 공유">↗</button></header><div className="body">
  <div className="photo">{record.image?<img src={record.image} alt={record.title}/>:'♪'}</div><div className="track"><strong>{record.title}</strong><small>{record.artist}</small></div><div className="tags">{record.tags.map(tag=><button key={tag} onClick={()=>navigate(`/search?q=${encodeURIComponent(tag)}`)}>#{tag}</button>)}</div>
  <div className="meta"><div><small>DATE</small><b>{record.date}</b></div><div><small>LOCATION</small><b>{record.location}</b></div><div><small>EMOTION</small><b>{record.emotion}</b></div><div><small>ACTIVITY</small><b>{record.activity}</b></div></div><div className="memo">{record.memo}</div>
  <div className="actions"><button className={liked?'active':''} onClick={()=>{toggleRecordLike(record.id);notify(liked?'좋아요를 취소했어요.':'좋아요를 눌렀어요.')}}>{liked?'♥':'♡'} 좋아요</button><button onClick={share}>↗ 공유</button><button className="primary" onClick={()=>setPicker(!picker)}>☷ 플리에 추가</button><button className="danger" onClick={remove}>삭제</button></div>
  {picker&&<div className="picker"><p>추가할 플레이리스트를 선택하세요.</p>{playlists.map(p=><button key={p.id} onClick={()=>{addToPlaylist(p.id,record.id);setPicker(false);notify(p.recordIds.includes(record.id)?'이미 추가된 기록이에요.':'플레이리스트에 추가했어요.')}}>{p.title}{p.recordIds.includes(record.id)?' · 추가됨':''}</button>)}</div>}
 </div><Toast show={!!toast}>{toast}</Toast></Page>;
}
