import { Fragment, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import styled from 'styled-components';
import Toast from '../components/Toast';
import { usePlivyStore } from '../store/PlivyStore';

const Page=styled.main`
 min-height:100vh;background:#f5f2ea;padding-bottom:90px;color:inherit;header{height:50px;display:grid;grid-template-columns:50px 1fr 50px;align-items:center;background:#c4d9a7;border-bottom:1px solid #92a77d}header h1{text-align:center;font:700 15px/1 var(--font-mono);letter-spacing:.15em}header button{height:50px;font-size:24px}.body{padding:20px}.hero{padding:21px;border-radius:13px;background:#19191f;color:#fff}.hero small{color:#f080a6}.hero h2{margin:10px 0 6px}.hero p{color:#aaa;font-size:11px}.list{display:grid;gap:11px;margin-top:18px}.item{display:grid;grid-template-columns:58px minmax(0,1fr) 70px;gap:10px;align-items:center;padding:11px;border:1px solid #ded9e1;border-radius:10px;background:#fff;color:inherit;cursor:pointer}.item.selected{border-color:#8f67d8;box-shadow:0 0 0 2px rgba(93,0,239,.08)}.cover{width:58px;height:58px;display:grid;place-items:center;border-radius:8px;background:radial-gradient(circle,#eee 0 14%,#c6bcd7 15% 35%,#9182ae 36% 52%,#ddd 53%)}.item h3{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:700 12px var(--font-mono)}.item p{margin-top:6px;color:#888;font-size:10px}.share{display:inline-flex;align-items:center;justify-content:center;box-sizing:border-box;width:70px;min-width:70px;max-width:70px;height:34px;padding:0 9px;white-space:nowrap;line-height:1;border:1px solid #d9cde4;border-radius:17px;background:#f7f2fb;color:#5d00ef;font-size:10px}.playlist-detail{margin:-4px 0 4px;padding:12px;border:1px solid #ded9e1;border-top:0;border-radius:0 0 10px 10px;background:#faf8fc}.playlist-detail p{font-size:10px;color:#888}.record-link{width:100%;padding:10px 4px;display:flex;justify-content:space-between;gap:10px;border-top:1px solid #ebe6ef;text-align:left;color:inherit}.record-link:first-of-type{margin-top:7px}.record-link strong{font-size:11px}.record-link small{color:#999}.empty{padding:10px 4px;color:#999;font-size:10px}.create{margin-top:15px;display:grid;grid-template-columns:1fr 76px;gap:8px}.create input{height:44px;padding:0 12px;border:1px solid #ddd;border-radius:8px}.create button{border-radius:8px;background:#c72f63;color:white}
 html[data-theme='dark'] &{background:#181a20;color:#f2f2f5}html[data-theme='dark'] & header{background:#2e3a2e}html[data-theme='dark'] & .item{background:#24262d;border-color:#41444d}html[data-theme='dark'] & .playlist-detail{background:#202229;border-color:#41444d}
`;
export default function FeaturePlaylists(){
 const navigate=useNavigate();const [params,setParams]=useSearchParams();const {playlists,records,addPlaylist}=usePlivyStore();const [title,setTitle]=useState('');const [toast,setToast]=useState('');const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),1600)};
 const selectedId=params.get('playlist');const selected=playlists.find(p=>p.id===selectedId);
 const openPlaylist=(id:string)=>{const next=new URLSearchParams(params);if(selectedId===id)next.delete('playlist');else next.set('playlist',id);setParams(next,{replace:true})};
 const share=async(id:string,name:string)=>{const url=`${location.origin}${location.pathname}#/playlists?playlist=${encodeURIComponent(id)}`;try{if(navigator.share){await navigator.share({title:`${name} · Plivy`,url});notify('공유 메뉴를 열었어요.')}else{await navigator.clipboard.writeText(url);notify('플레이리스트 링크가 복사되었어요.')}}catch{notify('공유를 취소했어요.')}};
 return <Page className="playlists-page"><header><button onClick={()=>navigate(-1)}>‹</button><h1>PLAYLISTS</h1><span/></header><div className="body"><section className="hero"><small>MEMORY MIX</small><h2>기억을 다시 재생해요</h2><p>기록 속 음악을 나만의 순서로 모아보세요.</p></section><section className="list">{playlists.map(p=>{const isSelected=selected?.id===p.id;const playlistRecords=p.recordIds.map(id=>records.find(r=>r.id===id)).filter(Boolean);return <Fragment key={p.id}><article className={`item ${isSelected?'selected':''}`} onClick={()=>openPlaylist(p.id)}><span className="cover">♪</span><div><h3>{p.title}</h3><p>{p.recordIds.length}개의 음악 기록</p></div><button className="share" onClick={e=>{e.stopPropagation();share(p.id,p.title)}}>↗ 공유</button></article>{isSelected&&<div className="playlist-detail"><p>{p.title}에 담긴 기록</p>{playlistRecords.length?playlistRecords.map(r=>r&&<button key={r.id} className="record-link" onClick={()=>navigate(`/detail/${r.id}`)}><strong>{r.title}</strong><small>{r.artist} ›</small></button>):<div className="empty">아직 추가된 기록이 없어요.</div>}</div>}</Fragment>})}</section><form className="create" onSubmit={e=>{e.preventDefault();if(!title.trim())return;addPlaylist(title);setTitle('');notify('플레이리스트를 만들었어요.')}}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="새 플레이리스트 이름"/><button>만들기</button></form></div><Toast show={!!toast}>{toast}</Toast></Page>;
}
